name: "Build Docker Image"
inputs:
  context:
    type: string
  tags:
    required: true
    type: string
  load:
    required: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.tags }}
