name: "Build Docker Image"
inputs:
  context:
    type: string
  tags:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker
      env:
        TAG: ${{ inputs.tags }}
        CONTEXT: ${{ inputs.context }}
      run: |
        docker build -t $TAG $CONTEXT
