name: "Build Docker Image"
inputs:
  context:
    type: string
  registry:
    required: true
    type: string
  tags:
    required: true
    type: string
  push:
    required: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

