name: Kubernetes project update

inputs:
  inputs:
    images:
      required: true
      type: string
    token:
      required: true
      type: string

runs:
  using: "composite"
  steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
        repository: cern-sis/kubernetes
        event-type: project-update
        token: ${{ inputs.token }}
        client-payload: '{"images":${{ inputs.images }}}'
