name: Kubernetes project new images

inputs:
  event-type:
    required: true
    type: string
  images:
    required: true
    type: string
  repo:
    required: true
    type: string
  token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        IMAGES=$(cat <<EOF
        ${{ inputs.images }}
        EOF
        )

        printf \
        'PAYLOAD={"images":%s}' \
        $(jq -nc '$ARGS.positional' --args $IMAGES) \
        >>$GITHUB_ENV

    - uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ inputs.repo }}
        event-type: project-${{ inputs.event-type }}
        token: ${{ inputs.token }}
        client-payload: ${{ env.PAYLOAD }}

