name: Build Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      tags:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          registry: ${{ inputs.registry }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
