name: Deploy QA

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      application:
        required: true
        type: string
      namespace:
        required: true
        type: string
      image:
        required: true
        type: string
      repository:
        required: false
        type: string
        default: cern-sis/kubernetes
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v2
      if: ${{ github.event_name == 'push'}}
      with:
        repository: ${{ inputs.repository }}
        event-type: deploy
        client-payload: '{"project":"${{ inputs.project }}", "application":"${{ inputs.application }}", "namespace":"${{ inputs.namespace }}", "image":"${{ inputs.image }}","new_tag":"${{ github.sha }}"}'
