name: Test Build QA

on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy QA
        uses: ./.github/workflows/deploy-qa.yml
        secrets: inherit
        with:
          project: scoap3
          application: scoap3-workflows
          namespace: scoap3-qa
          image: reg.cern.ch/cern/workflow
