name: Test Build QA

on:
  push:
    branches:
      - main
jobs:
  Build:
    uses: ./.github/workflows/deploy-qa.yml
    with:
      project: scoap3
      application: scoap3-workflows
      namespace: scoap3-qa
      image: reg.cern.ch/cern/workflow      
