name: Update image

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
      application:
        description: 'Application name'
        required: true
      namespace:
        description: 'Namespace'
        required: true
      image:
        description: 'Docker image'
        required: true
      new_tag:
        description: 'The new tag to deploy'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: normalize inputs
        id: normalized
        run: |
          PROJECT=${{ github.event.inputs.project || github.event.client_payload.project }}
          APPLICATION=${{ github.event.inputs.application || github.event.client_payload.application }}
          NAMESPACE=${{ github.event.inputs.namespace || github.event.client_payload.namespace }}
          IMAGE=${{ github.event.inputs.image || github.event.client_payload.image }}
          NEW_TAG=${{ github.event.inputs.new_tag || github.event.client_payload.new_tag }}
          echo "::set-output name=project::$PROJECT"
          echo "::set-output name=application::$APPLICATION"
          echo "::set-output name=namespace::$NAMESPACE"
          echo "::set-output name=image::$IMAGE"
          echo "::set-output name=new_tag::$NEW_TAG"

